"""OpenCode agent: writes opencode.json with Databricks-backed providers."""

from __future__ import annotations

import json
import os
import re
import signal
import subprocess

from ucode.agent_updates import available_npm_package_update
from ucode.config_io import (
    APP_DIR,
    ToolSpec,
    backup_existing_file,
    deep_merge_dict,
    read_json_safe,
    write_json_file,
    write_text_file,
)
from ucode.databricks import (
    ANTHROPIC_FAMILIES,
    build_auth_token_argv,
    build_opencode_base_urls,
    get_databricks_token,
    model_token_limits,
)
from ucode.state import mark_tool_managed, save_state
from ucode.telemetry import agent_version, ucode_version

from .args import LaunchOptions

# ucode keeps its config outside `~/.config/opencode`, so it never writes to the
# user's own config. Moving this path drops the `mcp` entries that `ucode mcp add`
# wrote here; re-running the command does not restore them, because ucode writes
# only when the server list changes.
OPENCODE_CONFIG_DIR = APP_DIR / "opencode-xdg" / "opencode"
OPENCODE_CONFIG_PATH = OPENCODE_CONFIG_DIR / "opencode.json"
OPENCODE_BACKUP_PATH = APP_DIR / "opencode-config.backup.json"
OPENCODE_AUTH_PLUGIN_PATH = OPENCODE_CONFIG_DIR / "plugin" / "ucode-auth.js"
OPENCODE_NPM_PACKAGE = "opencode-ai"
MINIMUM_OPENCODE_VERSION = (1, 0, 220)
MINIMUM_OPENCODE_VERSION_TEXT = "1.0.220"

SPEC: ToolSpec = {
    "binary": "opencode",
    # npm's `latest` tag currently points at an old 0.0.0 beta. Stay on the
    # stable v1 line for both fresh installs and updates.
    "package": f"{OPENCODE_NPM_PACKAGE}@1",
    "display": "OpenCode",
    "config_path": OPENCODE_CONFIG_PATH,
    "backup_path": OPENCODE_BACKUP_PATH,
}

PROVIDER_KEYS: list[list[str]] = [
    ["provider", "databricks-anthropic"],
    ["provider", "databricks-google"],
    ["provider", "databricks-oss"],
]

_AUTH_PLUGIN_TEMPLATE = """// Generated by ucode. Keep Databricks auth fresh for model requests.
import { execFile } from "node:child_process"
import { promisify } from "node:util"

const DATABRICKS_PROVIDERS = new Set([
  "databricks-anthropic",
  "databricks-google",
  "databricks-oss",
])
const AUTH_COMMAND = __AUTH_COMMAND__
const REFRESH_SKEW_MS = 120_000
const run = promisify(execFile)

let accessToken
let expiresAt = 0
let refreshPromise

function cacheToken(value) {
  accessToken = value
  expiresAt = Infinity
  try {
    const claims = JSON.parse(Buffer.from(value.split(".")[1], "base64url").toString())
    if (typeof claims.exp === "number") expiresAt = claims.exp * 1000
  } catch {}
}

async function mintToken() {
  try {
    const { stdout } = await run(AUTH_COMMAND[0], AUTH_COMMAND.slice(1), { encoding: "utf8" })
    const token = stdout.trim()
    if (!token) throw new Error("returned an empty token")
    cacheToken(token)
  } catch (error) {
    const detail = String(error.stderr || error.message || "").trim()
    throw new Error("ucode auth-token failed" + (detail ? ": " + detail : ""))
  }
}

function refreshToken() {
  if (!refreshPromise) refreshPromise = mintToken().finally(() => { refreshPromise = undefined })
  return refreshPromise
}

function requestWithToken(input, init, token) {
  const headers = new Headers(input instanceof Request ? input.headers : undefined)
  new Headers(init?.headers).forEach((value, key) => headers.set(key, value))
  headers.set("Authorization", "Bearer " + token)
  return { ...init, headers }
}

async function databricksFetch(input, init) {
  if (!accessToken || expiresAt <= Date.now() + REFRESH_SKEW_MS) await refreshToken()
  const attemptedToken = accessToken
  const response = await fetch(input, requestWithToken(input, init, attemptedToken))
  if (response.status !== 401) return response

  // Another concurrent request may already have refreshed this token.
  if (accessToken === attemptedToken) await refreshToken()
  return fetch(input, requestWithToken(input, init, accessToken))
}

export const UcodeDatabricksAuth = async () => ({
  config: async (config) => {
    for (const providerID of DATABRICKS_PROVIDERS) {
      const options = config.provider?.[providerID]?.options
      if (!options) continue
      if (!accessToken && typeof options.apiKey === "string") cacheToken(options.apiKey)
      options.fetch = databricksFetch
    }
  },
})
"""


def _parse_version(value: str) -> tuple[int, int, int] | None:
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", value)
    if match is None:
        return None
    major, minor, patch = match.groups()
    return int(major), int(minor), int(patch)


def _minimum_version_message() -> str | None:
    installed = agent_version(SPEC["binary"])
    parsed = _parse_version(installed)
    if parsed is None or parsed >= MINIMUM_OPENCODE_VERSION:
        return None
    return (
        f"OpenCode {installed} is too old. ucode requires OpenCode "
        f"{MINIMUM_OPENCODE_VERSION_TEXT} or newer for renewable Databricks authentication."
    )


def minimum_version_error() -> str | None:
    message = _minimum_version_message()
    if message is None:
        return None
    return f"{message} Update it with `npm install -g {SPEC['package']}`."


def is_update_available() -> tuple[str, str] | None:
    """Offer only stable OpenCode v1 updates, never npm's beta `latest` tag."""
    update = available_npm_package_update(OPENCODE_NPM_PACKAGE)
    if update is None:
        return None
    _, target = update
    parsed = _parse_version(target)
    if "-" in target or parsed is None or parsed[0] != 1:
        return None
    return update


def render_auth_plugin(state: dict) -> str:
    """Render the local OpenCode plugin that refreshes Databricks auth on demand."""
    argv = build_auth_token_argv(
        state["workspace"],
        state.get("profile"),
        use_pat=bool(state.get("use_pat")),
    )
    # A 401 must not return the same still-unexpired cached credential.
    argv.append("--force-refresh")
    return _AUTH_PLUGIN_TEMPLATE.replace("__AUTH_COMMAND__", json.dumps(argv))


def write_auth_plugin(state: dict) -> None:
    """Install the auto-discovered hook in ucode's isolated OpenCode config."""
    # Derive the path so tests that redirect OPENCODE_CONFIG_PATH stay isolated.
    path = OPENCODE_CONFIG_PATH.parent / "plugin" / OPENCODE_AUTH_PLUGIN_PATH.name
    write_text_file(path, render_auth_plugin(state))


def _resolve_model_selector(model: str, opencode_models: dict[str, list[str]]) -> str:
    """Return an OpenCode model selector in provider/model form when possible."""
    if model.startswith(("databricks-anthropic/", "databricks-google/", "databricks-oss/")):
        return model

    anthropic_models = opencode_models.get("anthropic") or []
    if model in anthropic_models:
        return f"databricks-anthropic/{model}"

    gemini_models = opencode_models.get("gemini") or []
    if model in gemini_models:
        return f"databricks-google/{model}"

    oss_models = opencode_models.get("oss") or []
    if model in oss_models:
        return f"databricks-oss/{model}"

    return model


def _oss_model_overlay(model: str, ua_header: dict[str, str]) -> dict:
    """Per-model overlay for an OSS model entry.

    All OSS models carry the User-Agent header; models with known token limits
    also pin `limit` (context + output) so OpenCode clamps `max_tokens` to a
    value the gateway accepts. OpenCode's schema requires both fields together,
    so the limits table always supplies both."""
    overlay: dict = {"headers": ua_header}
    limits = model_token_limits(model)
    if limits is not None:
        overlay["limit"] = limits
    return overlay


def render_overlay(
    model: str,
    token: str,
    opencode_base_urls: dict[str, str],
    opencode_models: dict[str, list[str]],
) -> tuple[dict, list[list[str]]]:
    """Return (overlay, managed_key_paths) for opencode.json."""
    auth_headers = {"Authorization": f"Bearer {token}"}
    # OpenCode hardcodes `User-Agent: opencode/<ver>` in session/llm.ts for
    # every provider, after the AI SDK's combineHeaders. The provider-level
    # `headers` are clobbered by that injection, but per-model `headers` are
    # merged AFTER and win — so the UA must live on each model entry.
    ua_header = {
        "User-Agent": f"ucode/{ucode_version()} opencode/{agent_version('opencode')}",
    }

    anthropic_models = opencode_models.get("anthropic") or []
    gemini_models = opencode_models.get("gemini") or []
    oss_models = opencode_models.get("oss") or []

    providers: dict = {}
    keys: list[list[str]] = [["model"]]
    if anthropic_models:
        # @ai-sdk/anthropic injects `eager_input_streaming: true` on tool defs;
        # the Databricks gateway's strict validator rejects it. opencode's
        # auto-disable in transform.ts skips models whose id contains "claude",
        # so we opt out per-model. The setting lives in per-call providerOptions,
        # which opencode reads from `models.<m>.options`, not provider `options`.
        anthropic_model_overlay = {
            "headers": ua_header,
            "options": {"toolStreaming": False},
        }
        providers["databricks-anthropic"] = {
            "npm": "@ai-sdk/anthropic",
            "options": {
                "baseURL": opencode_base_urls["anthropic"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": dict.fromkeys(anthropic_models, anthropic_model_overlay),
        }
        keys.append(["provider", "databricks-anthropic"])
    if gemini_models:
        providers["databricks-google"] = {
            "npm": "@ai-sdk/google",
            "options": {
                "baseURL": opencode_base_urls["gemini"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": {m: {"headers": ua_header} for m in gemini_models},
        }
        keys.append(["provider", "databricks-google"])
    if oss_models:
        providers["databricks-oss"] = {
            "npm": "@ai-sdk/openai",
            "options": {
                "baseURL": opencode_base_urls["oss"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": {m: _oss_model_overlay(m, ua_header) for m in oss_models},
        }
        keys.append(["provider", "databricks-oss"])

    overlay: dict = {"model": _resolve_model_selector(model, opencode_models)}
    if providers:
        overlay["provider"] = providers
    return overlay, keys


def write_tool_config(
    state: dict,
    model: str,
    token: str | None = None,
) -> tuple[dict, str]:
    backup_existing_file(OPENCODE_CONFIG_PATH, OPENCODE_BACKUP_PATH)
    if token is None:
        token = get_databricks_token(state["workspace"], state.get("profile"))
    opencode_base_urls = state.get("base_urls", {}).get("opencode") or build_opencode_base_urls(
        state["workspace"]
    )
    overlay, managed_keys = render_overlay(
        model,
        token,
        opencode_base_urls,
        state.get("opencode_models") or {},
    )
    existing = read_json_safe(OPENCODE_CONFIG_PATH)
    write_auth_plugin(state)
    providers = existing.get("provider")
    if isinstance(providers, dict):
        for stale in (
            "databricks-anthropic",
            "databricks-google",
            "databricks-openai",
            "databricks-oss",
        ):
            providers.pop(stale, None)
    merged = deep_merge_dict(existing, overlay)
    write_json_file(OPENCODE_CONFIG_PATH, merged)
    state = mark_tool_managed(state, "opencode", managed_keys)
    save_state(state)
    return state, token


def build_mcp_server_entry(argv: list[str]) -> dict:
    # A `local` MCP server runs a command over stdio; `command` is the full
    # argv. ucode registers the `ucode mcp-proxy ...` bridge here so OpenCode
    # never speaks HTTP+bearer directly — the proxy mints fresh tokens itself.
    return {
        "type": "local",
        "command": list(argv),
        "enabled": True,
    }


def write_mcp_server_config(name: str, argv: list[str]) -> bool:
    backup_existing_file(OPENCODE_CONFIG_PATH, OPENCODE_BACKUP_PATH)
    existing = read_json_safe(OPENCODE_CONFIG_PATH)
    mcp_servers = existing.get("mcp")
    if not isinstance(mcp_servers, dict):
        mcp_servers = {}
    removed = name in mcp_servers
    mcp_servers[name] = build_mcp_server_entry(argv)
    existing["mcp"] = mcp_servers
    write_json_file(OPENCODE_CONFIG_PATH, existing)
    return removed


def remove_mcp_server_config(name: str) -> bool:
    existing = read_json_safe(OPENCODE_CONFIG_PATH)
    mcp_servers = existing.get("mcp")
    if not isinstance(mcp_servers, dict) or name not in mcp_servers:
        return False
    mcp_servers.pop(name)
    existing["mcp"] = mcp_servers
    write_json_file(OPENCODE_CONFIG_PATH, existing)
    return True


def default_model(state: dict) -> str | None:
    """The model the first session starts on, until the user picks another in OpenCode.

    The lists in ``opencode_models`` are complete and carry no ranking — every model the workspace
    serves, for the user to choose from. Only the starting model needs a single answer, so take the
    Claude family pin ucode already computes for Claude Code (``claude_models``, highest tier first)
    rather than ranking the lists here. Falls back to any listed model when the workspace serves no
    Claude, and an explicit ``opencode_default_model`` (set by a managed config) wins outright.
    """
    if isinstance(state.get("opencode_default_model"), str):
        return state.get("opencode_default_model")
    opencode_models = state.get("opencode_models") or {}
    anthropic = opencode_models.get("anthropic") or []
    claude_pins = state.get("claude_models") or {}
    for family in ANTHROPIC_FAMILIES:
        pin = claude_pins.get(family)
        # Only a pin the anthropic provider actually lists is routable; a managed config can name
        # a family model that never made it into the bucket.
        if isinstance(pin, str) and pin in anthropic:
            return pin
    for models in (
        anthropic,
        opencode_models.get("gemini") or [],
        opencode_models.get("oss") or [],
    ):
        if models:
            return models[0]
    return None


def _configure_launch(state: dict) -> str:
    model = default_model(state)
    if not model:
        raise RuntimeError("No OpenCode model is configured.")
    _, token = write_tool_config(state, model)
    return token


def build_runtime_env(token: str, state: dict | None = None) -> dict[str, str]:
    env = os.environ.copy()
    env["OAUTH_TOKEN"] = token
    # opencode merges this file over the user's global config. It replaces a
    # top-level array instead of merging it, so this file carries no top-level
    # array — one would wipe the user's `disabled_providers`.
    env["OPENCODE_CONFIG"] = str(OPENCODE_CONFIG_PATH)
    return env


def launch(state: dict, tool_args: list[str], *, options: LaunchOptions) -> None:
    """Launch OpenCode with on-demand token refresh from its local plugin."""
    token = _configure_launch(state)
    env = build_runtime_env(token, state)

    proc = subprocess.Popen([SPEC["binary"], *tool_args], env=env)
    try:
        returncode = proc.wait()
    except KeyboardInterrupt:
        proc.send_signal(signal.SIGINT)
        returncode = proc.wait()

    raise SystemExit(returncode)


def validate_cmd(binary: str) -> list[str]:
    return [binary, "run", "say hi in 5 words or less"]


def validate_env(state: dict) -> dict[str, str]:
    workspace = state.get("workspace")
    if not workspace:
        raise RuntimeError("No workspace configured.")
    return build_runtime_env(get_databricks_token(workspace, state.get("profile")), state)
